name: riverpod_sample
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  freezed_annotation:
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  riverpod_generator:


  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
